import type { Metadata } from "next";
import DarkModeToggle from "./ui/navbar/dark-mode-toggle";
import "./globals.css";
import UltimateProvider from "./ultimate-provider";
import Navbar from "./ui/navbar/navbar";
import Footer from "./ui/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <UltimateProvider>

        <body>
          <Navbar />
          {children}
        </body>

        <Footer />
      </UltimateProvider>
    </html>
  );
}
